# Generated by Django 4.1.3 on 2022-11-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_api', '0002_alter_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='distance',
            field=models.IntegerField(),
        ),
    ]
